name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_PEM }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: "ubuntu"
        TARGET: "/var/www/html/"
        SCRIPT_AFTER: |
          sudo chown -R www-data:www-data /var/www/html
          sudo systemctl restart nginx 