name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_PEM }}
        known_hosts: unnecessary
        if_key_exists: replace

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key_path: ~/.ssh/id_rsa
        script: |
          cd /var/www/html
          sudo rm -rf *
          sudo cp -r /home/ubuntu/IA-Protoflio-by-AI/* .
          sudo chown -R www-data:www-data /var/www/html
          sudo systemctl restart nginx 