name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PEM }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy files
      run: |
        rsync -avz --delete ./ ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/
        ssh ubuntu@${{ secrets.EC2_HOST }} "sudo chown -R www-data:www-data /var/www/html && sudo systemctl restart nginx" 