name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PEM }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host *" > ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Deploy files
      run: |
        ssh -p 22 -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} "sudo su - root -c 'cd /var/www/html && rm -rf * && cp -r /home/ubuntu/IA-Protoflio-by-AI/* . && chown -R www-data:www-data /var/www/html && systemctl restart nginx'" 